### ISSUE TITLE
Training example command for NYU Depth v2

### ISSUE THREAD

**Issue by ganyz** [duanyiqun/DiffusionDepth#10]
Dear author:
    Could you provide the example commond to train the model on NYU Depth v2 like KITTI.

like :

$ python main.py --dir_data datta_path --data_name KITTIDC --split_json ../data_json/kitti_dp.json \
     --patch_height 352 --patch_width 906 --gpus 0,1,2,3 --loss 1.0*L1+1.0*L2+1.0*DDIM --epochs 30 \
     --batch_size 8 --max_depth 88.0 --save NAME_TO_SAVE \
     --model_name Diffusion_DCbase_ --backbone_module swin --backbone_name swin_large_naive_l4w722422k --head_specify DDIMDepthEstimate_Swin_ADDHAHI 

Thank you!

**Comment by duanyiqun** [comment]
Hi, sorry for the late reply due to busy days. 
You might be interested in https://github.com/duanyiqun/DiffusionDepth/issues/9 for this issue I think the command is ok. But still, I recommend implementing it on Kitti first as it is more stable.
