### ISSUE TITLE
A question about the DDIM loss.

### ISSUE THREAD

**Issue by ganyz** [duanyiqun/DiffusionDepth#11]
Dear author:
        Firstly nice work and thanks for code!
        A question about the ddim loss as shown in the fig.
![image](https://user-images.githubusercontent.com/30039015/229039510-39d1ded2-fdfd-495e-baea-44ae30a5ca20.png)

I don't know why , in the forward process (adding noise), it adopts the blur_depth_t (the x0 result of xt->x_t1->..->x0) instead of the gt_depth?

**Comment by duanyiqun** [comment]
hi there, the name blur depth_t here is just a name pattern. 

Please track the blur_depth transition. It should be refined depth latent. As we mentioned in the paper, gt_depth might be sparse in outdoor scenarios, so we use a self-diffusion formation.
