### ISSUE TITLE
Evaluation issue in HAHI head

### ISSUE THREAD

**Issue by HencyChen** [duanyiqun/DiffusionDepth#12]
Hi there, 

thanks for the great work.

During training, the gt_depth_map is used in depth_transform.t() function to transform the ground truth depth map as supervision. However, when performing evaluation, I'm wondering if gt_depth_map is available? If not (and it sould be the case), then how come the HAHI head can still be performed normally? 

(https://github.com/duanyiqun/DiffusionDepth/blob/62186966549e50122570ca7f87adb186d264ddb3/src/model/head/ddim_depth_estimate_res_swin_addHAHI.py#L102)

Thanks!

**Comment by duanyiqun** [comment]
Hi there, 

Thanks for your interest. The gt_depthmapt is only used for calculate the loss. If just for inference, it is not used in the forward path. 
I haven't write a serious "pure inference" code at this stage, the current code is for benchmark testing. 

A fast solution is just give a random value with the same shape (as we did for testing), the results will be ok. 
Or if you want to serving and increase the speed, it might need comment out gt_depth

**Comment by HencyChen** [comment]
Thanks for your fast response.
