### ISSUE TITLE
Is there a plan to publish checkpoints?

### ISSUE THREAD

**Issue by hutchinsonian** [duanyiqun/DiffusionDepth#13]

**Comment by zhangjic22** [comment]
Thanks for the great work! And I'm also looking forward to the release of the pre-trained models.

**Comment by duanyiqun** [comment]
Sorry for the late reply.  I release pre-trained models on the KITTI dataset for your reference: 
https://huggingface.co/claudecc/diffusiondepth/tree/main.
You may also refer to the updates on the README for more information.
cheers
