### ISSUE TITLE
Question about ddim loss

### ISSUE THREAD

**Issue by wyddmw** [duanyiqun/DiffusionDepth#16]
Hi, thanks for the awesome work! When I was reading the code, I noticed there are two implementations for computing the ddim loss which are ddim_loss and ddim_loss_gt, respectively. The primary difference is the choice of x_0. I would like to know if there is an obvious performance gap between these two choices and why using the latent predicted depth output is better. Thanks for the codes again!

**Comment by duanyiqun** [comment]
Hi there, 
ddim_loss_gt denotes direct diffusion on GT depth. 
On the KITTI dataset, it may cause severe overfitting limited to our experiments. 
If you have different observations we may update them here.

**Comment by wyddmw** [comment]
Thanks for your reply and this important conclusion. I'll close this issue.
