### ISSUE TITLE
 noise prediction

### ISSUE THREAD

**Issue by xiangli93** [duanyiqun/DiffusionDepth#18]
论文中是预测深度和加噪深度的差异。代码是预测噪声和设定噪声的差异。是一样的吗

**Comment by duanyiqun** [comment]
可以参考一下 https://github.com/huggingface/diffusers 
主流diffusion model的实现方式大部分都是采样n 个t时刻算预测噪声和diffuse 结果的差异，这里是一种近似，可以提升训练效率。

**Comment by xiangli93** [comment]
预测目标  训练效率会提高？
