### ISSUE TITLE
cannot find the mmdet3d you provided, hope can update, thnanks~

### ISSUE THREAD

**Issue by visonpon** [duanyiqun/DiffusionDepth#2]

**Comment by duanyiqun** [comment]
Do you have error logs? I only use the mmdet3d as a registry. In that case, any version in 2022 would be fine.

**Comment by duanyiqun** [comment]
please see the official repo to install mmdet3d 
https://github.com/open-mmlab/mmdetection3d/blob/master/docs/en/getting_started.md
