### ISSUE TITLE
Question about model train

### ISSUE THREAD

**Issue by ipwjincheng** [duanyiqun/DiffusionDepth#20]
Hi, I would like to ask whether the initial input xT of the network is obtained from random sampling or from depth gt plus noise during training

I noticed that you used a combination of loss in the code. Is it possible to restore pure noise through L1 and L2 loss? I really don't understand.

**Comment by ipwjincheng** [comment]
It looks like in your code, you're sampling a random noise and then passing discrete 0,50... The time series of 950 predicts the value at time x0. Add noise to the x0 value obtained at this time, and then perform the denoising process to get x '0. loss is calculated as l1 and l2loss of x0 and true depth and ddim loss of x0 and x '0. I don't know if I'm getting that right.

**Comment by duanyiqun** [comment]
I do not fully understand the question. But the process you described looks right. Please refer to DDIM for more details
