### ISSUE TITLE
Mismatch of clamp value for decoder

### ISSUE THREAD

**Issue by HencyChen** [duanyiqun/DiffusionDepth#27]
Dear @erjanmx @duanyiqun,

Thanks for the great work.

I'm wondering what's the value of eps of the decoder (i.e., the maximum clamp value). In paper you mentioned it's 1e6, however, in the code it seems to be 1e-6.

Code file: src/model/head/ddim_depth_estimate_res_swin_addHAHI.py, line 24
Paper: page 4 right column top sentence.

**Comment by duanyiqun** [comment]
Hi, 
Thank you very much for your interest. If my understanding to your question is right.  Please refer to https://github.com/duanyiqun/DiffusionDepth/blob/d121f8686838e477e7d4cfefd7bf2c9efea57c43/src/model/ops/depth_transform.py#L35 , in this line it show the camp value is in the denominator. So 1e-6 reverse to 1e6 roughly with minus one.

**Comment by HencyChen** [comment]
Thanks for the reply.
