### ISSUE TITLE
Training encoder decoder

### ISSUE THREAD

**Issue by dsshim0125** [duanyiqun/DiffusionDepth#3]
Hi, thank you for your brilliant works!

I have a question in training the encoder and decoder for mapping the depth to the latent space.

Are they trained beforehand and froze during training denoising process similar to latent diffusion or all the networks (encoder, decoder, and denoising function) are trained all together in an end-to-end manner?

**Comment by duanyiqun** [comment]
Hi there, 

I did have tested the pre-train way and train-in-end2end way. Limited to our experiments, these two methods do not suggest a clear difference. 

In this code, all the networks (encoder, decoder, and denoising function) are trained all together in an end-to-end manner.

**Comment by dsshim0125** [comment]
Thank you for your fast responses!
