### ISSUE TITLE
Missing install instructions - wrong python version and requirements.txt

### ISSUE THREAD

**Issue by drozzy** [duanyiqun/DiffusionDepth#34]
I think I'm doing something wrong.
In the README.md you say Python 3.9.13 is required.

But in the requirements.txt the package `open3d==0.13.0` is referenced, which in turn supports only python 3.8

**Comment by duanyiqun** [comment]
Thank you very much for your notice ! 
Sorry for any inconvenience may leaded, I have updated the readme.md based on this issue.
