### ISSUE TITLE
About kitti eigen split

### ISSUE THREAD

**Issue by wangjiyuan9** [duanyiqun/DiffusionDepth#42]
Hi there, thank you for your amazing work!
I noticed that in the paper, you mentioned the eigensplit you had used. However, I never found any eigen train split file like other projects.
And you said to use `prepare_KITTI_DP` to get the kitti data but never said how to get gt (for depth annotated data, we had gt, but eigen split != annotated one)

**Comment by wangjiyuan9** [comment]
To be specific, [there](https://github.com/shariqfarooq123/AdaBins/issues/58#issuecomment-1026654706) had said the difference between annotated depth and the projective point depth.

**Comment by wangjiyuan9** [comment]
And actually, I found no where to get the gt depth of the eigen train split, which is necessary for training :(

**Comment by duanyiqun** [comment]
Eigen train split is a widely used train split on Kitti dataset by many papers. And actually, you may have to check previous papers for Eigen's paper and split by yourself. 
Regards

**Comment by wangjiyuan9** [comment]
Thank you for your reply!
Yes, I know that the Eigen train split is a traditional split, but how to get the gt_depth which is training necessary? Did you do it as monodepth2??
