### ISSUE TITLE
About shell command of kitti

### ISSUE THREAD

**Issue by wangjiyuan9** [duanyiqun/DiffusionDepth#44]
Hi there, this is Amazing work, undoubtedly!
But I'd like to ask if you published something wrong in your training command:

$ python main.py --dir_data datta_path --data_name KITTIDC --split_json ../data_json/kitti_dp.json \
     --patch_height 352 --patch_width 

> 906

--GPUs 0,1,2,3 --loss 1.0*L1+1.0*L2+1.0*DDIM --epochs 30 \
     --batch_size 8 --max_depth 88.0 --save NAME_TO_SAVE \
     --model_name Diffusion_DCbase_ --backbone_module swin --backbone_name swin_large_naive_l4w722422k --head_specify DDIMDepthEstimate_Swin_ADDHAHI 

In your paper there are only 706*352, what is 906 ?

**Comment by duanyiqun** [comment]
Hi thanks for interest. 

This is actually crop_width*crop_height of input image. The final version used 706*352 size for training. However, for train from scratch 906 is more stable.

**Comment by wangjiyuan9** [comment]
Thanks for you reply!
