### ISSUE TITLE
Question regarding implementation and memory usage in the DiffusionDepth model

### ISSUE THREAD

**Issue by wangjiyuan9** [duanyiqun/DiffusionDepth#45]
Dear author:

I have been following your diffusion-depth for some time. This model is very powerful, and I really appreciate your work. 

My observation comes from the difference between the resnet version and the swin version of the code. 
In line 373-378 of (https://github.com/duanyiqun/DiffusionDepth/blob/208f7a5b9c29432d701e77666dbd8255d784323c/src/model/head/ddim_depth_estimate_res_swin_addHAHI.py):The upsampling make 400MB GPU memory usage for each iteration. However, if we directly add the tensors, as implemented in the resnet version, this problem doesn't occur. 
I noticed in your comments that you have also tried not using upsampling before. So my questions are: 
1. Did the results differ significantly when you directly added the tensors? Is upsampling necessary? 
2. Is there a way to increase memory usage when using upsampling? If possible, it could save up to 7GB of memory, greatly speeding up training. 
Really hope you can provide some guidance and reply, and I look forward to your support.

**Comment by wangjiyuan9** [comment]
Also about (https://github.com/duanyiqun/DiffusionDepth/issues/42). I know that the Eigen train split is a traditional split, but how to get the gt_depth which is training necessary? Did you do it as monodepth2??

**Comment by FliegenderVogel** [comment]
Why do you block me? It's only an issue...

**Comment by FliegenderVogel** [comment]
Same question!
